### PR TITLE
Added basic visualization 

### PR DESCRIPTION
**Pull request by sirusb**
if I understand correctly this will be converted to a react app, so I first merged with the original repo. 
Then I added my changes to the `DZCovidPred` folder.
Mainly I fetched data from Sohaib's api and visualize the different statistics. I will add more pages in the future.

### CODE REVIEW

**Comment by Taybou** [comment]
Hello @sirusb,

Yes, I think you should consider your implementation as a support service for visualization, and focus only on data retrieval, adaptation and exposure for integration with react UI

Otherwise, if you have another idea, don't hesitate to share :D

Cheers

**Comment by assem-ch** [comment]
@Taybou  can you give me your email to add you to slack

**Comment by assem-ch** [comment]
@Taybou  I want to have similar stats 
from: http://covid19.sante.gov.dz/carte/
to: http://dzcovid19.pythonanywhere.com/

**Comment by sirusb** [comment]
@Taybou 
Yeah, I think at the end will can go all react. as in the back-end, there are not really many complex things, probably just the prediction, which I don't have much data now, we will need python for that .

**Comment by sirusb** [comment]
@assem-ch 
Yeah, it would be great,if can fetch all those info.

**Comment by Taybou** [comment]
Thank you @sirusb

**Pull request merged**
