### PR TITLE
Init react app

### PR DESCRIPTION
**Pull request by Taybou**

### CODE REVIEW

**Comment by Taybou** [comment]
Request reviewer: @01walid 😂

@01walid can you please give us some access, for example to add labels or reviewers...

Thank you

**Comment by 01walid** [comment]
> Request reviewer: @01walid joy
> 
> @01walid can you please give us some access, for example to add labels or reviewers...
> 
> Thank you

Check with @assem-ch

**Comment by assem-ch** [comment]
@Taybou  added as maintainer

**Comment by Taybou** [comment]
All right, I'm going to merge this PR, we're trying to move forward for now because we're still in the configuration steps.

Thank you

**Pull request merged**
